### ISSUE TITLE
Roadmap to 0.1 (first available version)

### ISSUE THREAD

**Issue by aralroca** [brisa-build/brisa#1]
<p align="center"> <img src="https://github.com/brisa-build/brisa/assets/13313058/06a1967f-d6e8-4497-ba6d-51b176abf663" height="128" />
<h2 align="center">ROADMAP TO 0.1 (first version) 🚀</h2>
</p>

## JSX Components

- [x] Implement jsx-runtime
- [x] async components
- [x] async components error component (Component.error)
- [x] async components loading component (Component.suspense)
- [x] Improve context communication between server and web
- [x] #85
- [x] #88
- [x] #87
- [x] #138
- [x] #123
- [x] #140
- [x] #157
- [x] #75
- [x] #182

### Client (web components)

- [x] Implement state
- [x] Implement events 
- [x] Implement web-components in functional JSX components
- [x] Implement reactivity in state and props changes
- [x] Implement effects, onMount, derived and cleanup in web-components
- [x] Serialize and deserialize objects as props in server components consuming web componentes and web-compoments consuming web-components
- [x] Support rendering SVGElements in web components
- [x] Support `export const props = ['propName']` as optional to fix reactivity in web-components props when using props spread `<div {...exampleProps} />`
- [x] Support custom hooks
- [x] Implement attribute `key` to unmount / mount web components when change
- [x] Support `ref` attribute to elements
- [x] implement `createPortal`. Portals to support shared modals, etc
- [x] #9
- [x] #13
- [x] #15
- [x] #20 
- [x] #23
- [x] #19
- [x] https://github.com/aralroca/brisa/issues/32
- [x] #43
- [x] #46
- [x] #45
- [x] #258
- [x] #69
- [x] #77
- [x] #81
- [x] #152
- [x] #369
- [x] #506

### Server components

- [x] Add request as second param of server components (to access to params, cookies, url, headers, etc)
- [x] stream rendering
- [x] #29
- [x] #95
- [x] #98
- [x] #100
- [x] #165
- [x] #47
- [x] #73

## Architecture

- [x] Routing pages in Next.js way /pages/index.ts, /src/pages/index.ts, /src/pages/user/[slug].ts, /src/pages/user/[...slug].ts
- [x] api folder
- [x] access variable of dynamic routing
- [x] hotreloading
- [x] Assets (images, favicon, manifest, etc)
- [x] use env variables inside server routes
- [x] \_404 and \_500 page support
- [x] support layouts (layouts.(tsx|ts|js) / layouts/index(tsx|ts|js)), it returns the request to render different layouts depending the page
- [x] support middleware - middleware.(tsx|ts|js) / middleware/index.(tsx|ts|js)
- [x] support "export Head" component in pages to overwrite head content (meta, links...) on the layout, using "id"
- [x] Support websockets - websockets.(tsx|ts|js) / websockets/index.(tsx|ts|js) and add "ws" to RequestContext
- [x] Support `responseHeaders` function that returns the headers object, in the page level and also layout level. Useful to control the cache or add some X-headers.
- [x] #41
- [x] #306
- [x] #482

## Testing

- [x] [**`render`**. Supporting "Server Components" (HTML elements) and "Web Components" (custom elements). Should also support a `Response` to use it together with `serveRoute` to render pages.](https://github.com/brisa-build/brisa/issues/144)
- [x] [**`serveRoute`**. Fetch some page or API endpoint and return the response.](https://github.com/brisa-build/brisa/issues/144)
- [x] [The `render` and `serveRoute` returns: **`container`** and **`cleanup`**](https://github.com/brisa-build/brisa/issues/144). 
- [x] [The `render` work with **server actions** and possible to test them](https://github.com/brisa-build/brisa/issues/144)
- [x] [The `render` work with **signals** and custom elements](https://github.com/brisa-build/brisa/issues/144)
- [x] [The `render` should support `locale` as option to test i18n translations in server and web components](https://github.com/brisa-build/brisa/issues/144)
- [x] [`waitFor` to wait for an "expect" assertion to pass.](https://github.com/brisa-build/brisa/issues/144)
- [x] [**`userEvent`** to simulate user events like click, type, hover, focus, etc.](https://github.com/brisa-build/brisa/issues/144)
- [x] [**`debug`** (similar to `console.log(document.documentElement.outerHTML)` but prettier and with colors in the HTML elements](https://github.com/brisa-build/brisa/issues/144)
- [x] [**`cleanup`** method to clear the document and server actions register](https://github.com/brisa-build/brisa/issues/144)
- [x] [Matchers to test DOM: `toBeChecked`, `toHaveAttribute`,  `toHaveTagName`, `toHaveTextContent`, `toBeInTheDocument`, etc...](https://github.com/brisa-build/brisa/issues/144)

## Brisa API

- [x] `dangerHTML` helper: an alternative to React `dangerouslySetInnerHTML` allowing HTML without creating a new node
- [x] Implement support of`dangerHTML` in web-components 
- [x] #38
- [x] #74
- [x] #124
- [x] #376
- [x] [expose `fileSystemRouter` API if you want to use in custom server](https://github.com/brisa-build/brisa/pull/386)
- [x] #484

## CLI

- [x] CLI dev
- [x] CLI build
- [x] CLI start
- [x] CLI build: gzip assets
- [x] #192
- [x] Allow different port than 3000 using "bun dev -p 8080"
- [x] #421 
- [x] #420

## Internationalization (i18n)

- [x] i18n routing - i18n.(tsx|ts|js) / i18n/index.(tsx|ts|js)
- [x] i18n navigation
- [x] Support to share context from the middleware to the components
- [x]  i18n routing extra: localeDetection
- [x]  i18n routing extra:  save preferred language to `BRISA_LOCALE` cookie
- [x] i18n routing extra: domains
- [x] i18n consume translations in an easy way
- [x]  i18n routing extra:  translate page name 
- [x]  i18n routing extra: navigation with translated pages 
- [x]  i18n routing extra: hreflang
- [x] #12
- [x] #54
- [x] #56
- [x] #64
- [x] #66
- [x] #55

## Configuration

- [x] trailingSlash (false by default but possible to change via configuration)
- [x] #3
- [x] #133
- [x] #25
- [x] #146
- [x] #167
- [x] #429
- [x] #451 

## Optimizations

- [x] #50
- [x] #52

## CSS

- [x] #36
- [x] #48
- [x] #136
- [x] #156

## DX

- [x] Create a bun template
- [x] enable type-safe consuming translations
- [x] https://github.com/aralroca/brisa/issues/34
- [x] #82
- [x] #31
- [x] #92
- [x] #333
- [x] #153
- [x] #67

## Exports

- [x] #59
- [x] #60
- [x] #108
- [x] #195
- [x] #447
- [x] #318
- [x] #40

Next: [1.0 Routemap](https://github.com/brisa-build/brisa/issues/197)
